---

- name: Création des users
  hosts: all
  become: yes
  become_user: Abdel
  tasks:
    - name: installation apache server
      yum:
        name: httpd
        state: present
    - name: Redémarrer le service
      service:
        name: httpd
        state: started
        
        
   - name: installation mariadb
     hosts: [db]
     roles:
       - mariadb


   
