---

- name: Création des users
  hosts: all
  become: yes
  remote_user: Abdel
  roles:
   - create_user
   
- name: Installation du serveur web
   hosts: [ServeurWEB]
   roles:
    -SQLWeb
        
        
   - name: installation mariadb
     hosts: [db]
     roles:
       - mariadb


   
