---

- name: Création des users
  hosts: 192.168.56.101
  become: yes
  become_user: Abdel
  tasks:
    - name: installation apache server
      yum:
        name: httpd
        state: present
    - name: Redémarrer le service
      service:
        name: httpd
        state: started
        
        
   - name: installation mariadb
     yum:
       name: mariadb
       state: present
   - name: Redémarrer le service une fois installé
     service:
       name:
       state: started
     


   
